### PR TITLE
Added modelDescription field to device description

### PR DESCRIPTION
**Pull request by dennis-hh**
My devices have a modelDescription field inside the device description I have to rely on. I could rely on my own fork, but as this is the original project, I thought I should give it a shot to make a pull request.

### CODE REVIEW

**Comment by thibauts** [comment]
Hi, thanks for your PR. This makes me wonder what will happen if the listed fields are not available in a device description. I checked the specs [here](http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf) (page 27, PDF page 31) and even some fields that were already listed before your PR seem to be optional.

Could you please test what happens when the code tries to extract a non-existant field ? Ideally the field wouldn't be available in the returned description (undefined).

**Comment by dennis-hh** [comment]
I quickly added "foo" as an extractable field. This is the result:
`foo: undefined,
  UDN: 'uuid:234a9ff1-4b2c-4636-80b8-6ae41b4f02b9',`
So it gracefully defaults to "undefined".

**Comment by thibauts** [comment]
Great :)

Could you update the `extractFields` function with this code in your PR ?

``` javascript
function extractFields(node, fields) {
  var data = {};
  fields.forEach(function(field) {
    var value = node.findtext('./' + field);
    if(typeof value !== 'undefined') {
      data[field] = value;
    }
  });
  return data;
}
```

This way the key won't even be defined in the output.

**Comment by dennis-hh** [comment]
Done!

**Comment by dennis-hh** [comment]
Thanks. Any chance of releasing a new version on npmjs anytime, soon? :)

**Comment by thibauts** [comment]
Great :)

Version updated (patch) and pushed to npm. 

Thanks for your PR !

**Pull request merged**
